export interface ValueFormPredict {
  edad_cardiovascular: number,
  targa: number,
  hepatitisB: number,
  hepatitisC: number,
  VIH: number,
  sida: number,
  tuberculosis: number,
  insRespiratoria: number,
  alcoholismo: number,
  anemia: number,
  desnutricion: number,
  cancer: 0,
  diarrea: 0,
  diabetes: number,
  sepsis: number,
  neumonia: number,
  covid: number,
  test1: number,
  test2: number,
  test3: number,
}
