export interface ValueFormPredict {
  edad_cardiovascular: number,
  sex: number,
  usoAnticoagulantes: number,
  usoMedicamentosPresion: number,
  cirugiasPrevias: number,
  actividadesExtenuantes: number,
  antecedentesCardiovasculares: number,
  antecedentesCardiacos: number,
  antecedentesRespiratorios: number,
  antecedentesRenales: number,
  antecedentesDiabeticos: number,
  antecedentesHipertension: number,
  antecedentesObesidad: number,
  antecedentesColesterol: number,
  fumador: number,
  diabetes: number,
  actividadFisica: number,
  alimentacion: number,
  consumoAlcohol: number,
  nivelEstres: number,

}
